WeSports/config/routes.rb
Wesports::Application.routes.draw do
  resources :games
  resources :players, only: [:show]
  get 'games/:id/join', to: 'games#join', as: :join_game
  root 'games#login'
  
  # get '/auth/google_oath2/callback', to: 'sessions#omniauth'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  get '/quick_login/:id', to: 'sessions#quick_login', as: :quick_login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

end

WeSports/app/models/player.rb
class Player < ActiveRecord::Base
  validates :username, :email, presence: true
  validates :email, uniqueness: true
  has_and_belongs_to_many :games, join_table: 'games_players'
  
  def self.create_from_omniauth(auth)
        Player.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.email = auth['info']['email']
        end
  end

  def find_games_created()
    return Game.where(:owning_player_id => id)
  end

  # def self.check_player_exist(player_id)
  #   if exists?(id: player_id)
  #     notice = ""
  #     valid = true
  #   else
  #     notice = "Error: Player does not exist"
  #     valid = false
  #   end
  #   return valid, notice
  # end
end

WeSports/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    id = params[:id]
    @player = Player.find(id) # look up movie by unique ID
    @games_created = @player.find_games_created()
    @games_joined = @player.games
    # will render app/views/players/show.<extension> by default
  end
end

WeSports/app/views/players/show.html.haml
-# in app/views/movies/show.html.haml

%h3 Details about #{@player.username}

%div.detailsList
  %ul
    %li
      Email:
      = @player.email
    %li
      Name:
      = @player.username

%br
%h3 Games Joined:

%table#games.table.table-striped.col-md-12
  %thead
    %tr
      %th Sport Name
      %th Zip Code
      %th Start Time
      %th End Time
      %th Slots Available
      %th Game Info
  %tbody
    - @games_joined.each do |game|
      %tr
        %td= game.sport_name
        %td= game.zipcode
        %td= game.game_start_time
        %td= game.game_end_time
        %td= game.spots_left
        %td= link_to "More about #{game.sport_name}", game_path(game)


%br
%h3 Games Created:

%table#games.table.table-striped.col-md-12
  %thead
    %tr
      %th Sport Name
      %th Zip Code
      %th Start Time
      %th End Time
      %th Slots Available
      %th Game Info
  %tbody
    - @games_created.each do |game|
      %tr
        %td= game.sport_name
        %td= game.zipcode
        %td= game.game_start_time
        %td= game.game_end_time
        %td= game.spots_left
        %td= link_to "More about #{game.sport_name}", game_path(game)

= button_to 'Back to Games list', games_path, :method => :get, :class => 'btn btn-primary btn-back'