WeSports/config/routes.rb
Wesports::Application.routes.draw do
  resources :games
  resources :players, only: [:show]
  get 'games/:id/join', to: 'games#join', as: :join_game
  root 'games#login'
  
  # get '/auth/google_oath2/callback', to: 'sessions#omniauth'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new'
  get '/quick_login/:id', to: 'sessions#quick_login', as: :quick_login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

end

WeSports/app/models/game.rb
class Game < ActiveRecord::Base
    has_and_belongs_to_many :players, join_table: 'games_players'
    belongs_to :owning_player, :class_name => 'Player', :foreign_key => 'owning_player_id'

    def player_created_game?(player_id)
        return owning_player.id == player_id
    end

    def player_joined_game?(player_id)
        return players.exists?(player_id)
    end

    def slots_taken
        return players.length
    end

    def player_join_game(player_id)
        if not player_joined_game?(player_id)
            player = Player.find(player_id)
            players << player
            return "Successfully Joined Game"
        else
            return "Already joined game"
        end
    end

    def spots_left
        if slots_to_be_filled.nil?
            return 0
        elsif slots_taken == 0
            return slots_to_be_filled
        else
            return slots_to_be_filled - slots_taken
        end
    end

    def update_game(game_params)
        valid, notice = Game.check_valid_game(game_params)
        if valid
            if game_params[:slots_to_be_filled].to_i < slots_taken
                valid = false
                notice = "Error: More Slots Taken (#{slots_taken}) than Available"
            else
                update_attributes!(game_params)
                notice = "Successfully updated game"
            end
        end

        return valid, notice
    end

    def self.add_game(game_params, player_id)
        valid, notice = Game.check_valid_game(game_params)
        if valid
            g = create!(game_params)
            g.owning_player = Player.find(player_id)
            g.save
            notice = "Successfully created #{game_params[:sport_name]} game"
        end
        return valid, notice
    end

    def self.check_valid_game(game_params)
        if game_params[:sport_name].empty? or game_params[:zipcode].empty?
            notice = "Error: Missing Zip Code or Sport Name Fields"
            valid = false
        elsif game_params[:slots_to_be_filled].empty? or game_params[:slots_to_be_filled].to_i == 0
            notice = "Error: Total Slots Available not valid"
            valid = false
        else
            notice = ""
            valid = true
        end
        return valid, notice
    end

    def self.check_game_exist(game_id)
        if exists?(id: game_id)
            notice = ""
            valid = true
        else
            notice = "Error: Game does not exist"
            valid = false
        end
        return valid, notice
    end

end

WeSports/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_game_created_by_player, only: [:edit, :update, :destroy]

  private

  def require_game_created_by_player
    @game = Game.find params[:id]
    if not @game.player_created_game?(session[:user_id])
      flash[:notice] = "Cannot edit a game you did not create"
      redirect_to games_path
    end
  end

  public

  def show
    id = params[:id] # retrieve movie ID from URI route
    @game = Game.find(id) # look up movie by unique ID
    @player_joined_game = @game.player_joined_game?(session[:user_id])
    @player_owns_game = @game.player_created_game?(session[:user_id])
    @players = @game.players
    address = ""
    if @game.address
      address = @game.address.gsub(' ','+') + "+"
    end
    @location = "https://www.google.com/maps/place/" + address + @game.zipcode
    # will render app/views/movies/show.<extension> by default
  end

  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'name'
      ordering,@name_header = {:sport_name => :asc}, 'bg-warning hilite'
    when 'start'
      ordering,@start_header = {:game_start_time => :asc}, 'bg-warning hilite'
    end
    @player = Player.find(session[:user_id])
    @games_player_joined = @player.games
    @games = Game.where.not(id: @games_player_joined.ids)

    if @player.nil?
      redirect_to '/login'
    end
    @name = params[:name_search] || session[:name_search] || nil
    @zip = params[:zip_search] || session[:zip_search] || nil
    @available = params[:only_available] || nil

    if params[:sort] != session[:sort] or params[:name_search] != session[:name_search] or params[:zip_search] != session[:zip_search] or @available != session[:only_available]
      session[:sort] = sort
      session[:name_search] = @name
      session[:zip_search] = @zip
      session[:only_available] = params[:only_available]
      redirect_to :sort => sort, :name_search => @name, :zip_search => @zip, :only_available => @available and return
    end

    @games = Game.all().order(ordering)
    if not params[:name_search].blank?
      sport = params[:name_search].downcase
      @games = @games.where("lower(sport_name) LIKE :name_search", name_search: "%#{sport}%")
    end
    if not params[:zip_search].blank?
      zip = params[:zip_search].downcase
      @games = @games.where("zipcode LIKE :zip_search", zip_search: "%#{zip}%")
    end
    if params[:only_available] == "1"
      @games = @games.select {|game| game.spots_left > 0}
    end

  end

  def new
    # default: render 'new' template
  end

  def create
    valid, notice = Game.add_game(game_params(), session[:user_id])
    flash[:notice] = notice
    if valid
      redirect_to games_path
    else
      redirect_to new_game_path
    end
  end

  def edit

  end

  def join
    @game = Game.find params[:id]
    player_id = session[:user_id]
    notice = @game.player_join_game(player_id)
    flash[:notice] = notice
    redirect_to game_path(@game)
  end

  def update
    valid, notice = @game.update_game(game_params())
    flash[:notice] = notice
    if valid
      redirect_to game_path(@game)
    else
      redirect_to edit_game_path(@game)
    end
  end

  def destroy
    @game.destroy
    flash[:notice] = "Game '#{@game.sport_name}' deleted."
    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:sport_name, :address, :zipcode, :slots_to_be_filled, :game_start_time, :game_end_time)
  end
end

WeSports/app/views/games/edit.html.haml
-# edit.html.haml using partial
= button_to 'Back to Games list', games_path, :method => :get, :class => 'btn btn-primary btn-back'

%h2 Edit Existing Game

= form_tag game_path(@game), :method => :put, :id => 'edit_form' do

  = label :game, :sport_name, 'Sport Name'
  = text_field :game, "sport_name", placeholder: @game.sport_name

  = label :game, :address, 'Address'
  = text_field :game, "address", placeholder: @game.address

  = label :game, :zipcode, 'Zip Code'
  = text_field :game, "zipcode", placeholder: @game.zipcode

  = label :game, :slots_to_be_filled, 'Total Slots Available'
  = number_field :game, :slots_to_be_filled, min: 1, placeholder: @game.slots_to_be_filled

  = label :game, :game_start_time, 'Game Start Time'
  = datetime_select :game, :game_start_time, default: @game.game_start_time, ampm: true
  %br
  = label :game, :game_end_time, 'Game End Time'
  = datetime_select :game, :game_end_time, default: @game.game_end_time, ampm: true
  %br
  = submit_tag 'Update Game Info', :class => 'btn btn-primary'

WeSports/app/views/games/index.html.haml
-#  This file is app/views/games/index.html.haml
%div.welcome
  %h1 Welcome #{@player.username}!
  %h3 Games for you

-# = form_tag movies_path, :method => :get, :id => 'ratings_form' do
-#   = hidden_field_tag "title_sort", true if @title_header
-#   = hidden_field_tag ":release_date_sort", true if @date_header
-#   Include:
-#   - @all_ratings.each do |rating|
-#     = rating
-#     = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
-#   = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'btn btn-primary'

%div.filter
  = form_tag games_path, :method => :get, :id => 'available_form' do
    Only available games:
    = check_box_tag :only_available, 1, @available, :id => "only_available"
    = submit_tag 'Refresh', :id => 'is_available_submit', :class => 'btn btn-primary btn-info'

  = form_tag(games_path, :method => "get") do
    #search-bar.input-group
      = search_field_tag :name_search, params[:name_search], placeholder: "Enter a Sport", :id => "search-name-bar"
      #search-button.input-group-btn
        = button_tag "Name Filter", :class => 'btn btn-info', :name => nil

  = form_tag(games_path, :method => "get") do
    #search-bar.input-group
      = search_field_tag :zip_search, params[:zip_search], placeholder: "Enter a Zipcode", :id => "search-zipcode-bar"
      #search-button.input-group-btn
        = button_tag "Zip Filter", :class => 'btn btn-info', :name => nil

%table#games.table.table-striped.col-md-12
  %thead
    %tr
      %th{:class => @name_header}= link_to 'Sport Name', games_path(:sort => 'name', :name_search => @name, :zip_search => @zip, :only_available => @available), :id => 'name_header'
      %th Zip Code
      %th{:class => @start_header}= link_to 'Start Time', games_path(:sort => 'start', :name_search => @name, :zip_search => @zip, :only_available => @available), :id => 'start_header'
      %th End Time
      %th Slots Available
      %th Game Info
  %tbody
    - @games.each do |game|
      %tr
        %td= game.sport_name
        %td= game.zipcode
        %td= game.game_start_time
        %td= game.game_end_time
        %td= game.spots_left
        %td= link_to "More about #{game.sport_name}", game_path(game)

= button_to 'Add new game', new_game_path, method: :get, :class => "btn btn-info"

= button_to 'Profile Page', player_path(@player), method: :get, :class => "btn btn-info"

WeSports/app/views/games/login.html.haml
<body>
<div id = "login"> 
<h1 class = "welcomeMessage">Welcome To We Sports!</h1>


= button_to "Log in with your Google account", '/auth/google_oauth2' , :class => 'button blue'
</div>

</body>

WeSports/app/views/games/new.html.haml
= button_to 'Back to Games list', games_path, :method => :get, :class => 'btn btn-primary btn-back'
%h2 Create New Movie

= form_tag games_path, :id => 'new_form' do

  = label :game, :sport_name, 'Sport Name'
  = text_field :game, "sport_name"

  = label :game, :address, 'Address'
  = text_field :game, "address"

  = label :game, :zipcode, 'Zip Code'
  = text_field :game, "zipcode"


  = label :game, :slots_to_be_filled, 'Total Slots Available'
  = number_field :game, :slots_to_be_filled, min: 1

  = label :game, :game_start_time, 'Game Start Time'
  = datetime_select :game, :game_start_time, default: 3.days.from_now, ampm: true
  %br
  = label :game, :game_end_time, 'Game End Time'
  = datetime_select :game, :game_end_time, default: 3.days.from_now, ampm: true
  %br
  = submit_tag 'Save Changes', :class => 'btn btn-primary'

WeSports/app/views/games/show.html.haml
-# in app/views/movies/show.html.haml
= button_to 'Back to Games list', games_path, :method => :get, :class => 'btn btn-primary btn-back'

%h3 Details about #{@game.sport_name}

%div.detailsList
  %ul
    %li
      Address:
      = @game.address
    %li
      Zip Code:
      = @game.zipcode
    %li
      Start Time:
      = @game.game_start_time.strftime("%B %d, %Y, %I:%M %p")
    %li
      Slots Left Available:
      = @game.spots_left
    %li
      = link_to "Open Location in Maps", @location

%h3 Players Joined

%div.playersList
  %ul
    - @players.each do |p|
      %li= link_to "#{p.username}", player_path(p)

%div.gameButtons
  - if @game.spots_left > 0 and not @player_joined_game
    = button_to 'Join Game', join_game_path(@game), :method => :get, :confirm => 'Are you sure to Join this Game?', :class => 'btn btn-primary btn-game'
  - if @player_owns_game
    = button_to 'Edit', edit_game_path(@game), :method => :get, :class => 'btn btn-primary btn-game'
    = button_to 'Delete', game_path(@game), :method => :delete, :confirm => 'Are you sure to delete this Game?', :class => 'btn btn-primary btn-game'